// =============================================
// UPSTREAM DEV PORTAL — Data
// Edit this file to add/remove apps & ERP envs
// =============================================

export const WEB_APPS = [
  {
    id: "meta-mini",
    name: "META MINI APPS",
    desc: "META landing page — Oracle APEX",
    url: "http://meta.niaganusaabadi.co.id:8080/ords/r/metaapex/landing-page-application/home",
    host: "meta.niaganusaabadi.co.id",
    icon: "📱",
    color: "green",
    badge: "prod",
    cat: "prod",
  },
  {
    id: "it-pmo",
    name: "IT PMO PROC",
    desc: "IT Project Management process",
    url: "http://leto.sonia.net:8080/ords/r/xtd/itproc/list",
    host: "leto.sonia.net",
    icon: "⚙️",
    color: "cyan",
    badge: "tool",
    cat: "tool",
  },
  {
    id: "kdk-prod",
    name: "KDK PROD",
    desc: "KDK Apps — production",
    url: "http://192.168.102.83:8080/ords/kdk/r/kdk-apps/login",
    host: "192.168.102.83",
    icon: "🏭",
    color: "green",
    badge: "prod",
    cat: "prod",
  },
  {
    id: "kdk-dev",
    name: "KDK DEV",
    desc: "KDK Apps — development",
    url: "http://192.168.102.83:8080/ords/kdkdev/r/kdk-apps/login",
    host: "192.168.102.83",
    icon: "🔨",
    color: "amber",
    badge: "dev",
    cat: "dev",
  },
  {
    id: "frits",
    name: "FRITS",
    desc: "Form Request IT System",
    url: "https://apex.oracle.com/pls/apex/r/nti_apps/form-request-it",
    host: "apex.oracle.com",
    icon: "🎫",
    color: "cyan",
    badge: "tool",
    cat: "tool",
  },
  {
    id: "eam",
    name: "EAM",
    desc: "Enterprise Asset Management",
    url: "http://leto.sonia.net:8080/ords/r/eam/enterprise-asset-management/login",
    host: "leto.sonia.net",
    icon: "🏗️",
    color: "violet",
    badge: "prod",
    cat: "prod",
  },
  {
    id: "permadi",
    name: "PERMADI",
    desc: "NTI MIS Application",
    url: "https://apex.oracle.com/pls/apex/r/nti_mis/a272678/login",
    host: "apex.oracle.com",
    icon: "📊",
    color: "violet",
    badge: "prod",
    cat: "prod",
  },
  {
    id: "submit-ticket",
    name: "Submit Ticket",
    desc: "Freshdesk — open new ticket",
    url: "https://nti-support.freshdesk.com/support/tickets/new",
    host: "freshdesk.com",
    icon: "📨",
    color: "red",
    badge: "support",
    cat: "support",
  },
  {
    id: "ticketing-faq",
    name: "Ticketing FAQ",
    desc: "Freshdesk solutions & FAQ",
    url: "https://nti-support.freshdesk.com/support/solutions/folders/51000338037",
    host: "freshdesk.com",
    icon: "📋",
    color: "red",
    badge: "support",
    cat: "support",
  },
  {
    id: "meva",
    name: "MEVA (JKT)",
    desc: "OutSystems MEVA — Jakarta",
    url: "https://personal-foajtp26.outsystemscloud.com/MEVA/Login",
    host: "outsystemscloud.com",
    icon: "🌐",
    color: "cyan",
    badge: "prod",
    cat: "prod",
  },
  {
    id: "siati",
    name: "SIATI (JKT)",
    desc: "SIATI NNA — Jakarta",
    url: "http://siati.niaganusaabadi.co.id/login",
    host: "niaganusaabadi.co.id",
    icon: "📡",
    color: "green",
    badge: "prod",
    cat: "prod",
  },
  {
    id: "tableau",
    name: "Tableau (NNA JKT)",
    desc: "Analytics server — Jakarta",
    url: "http://aino2.sonia.net:8000",
    host: "aino2.sonia.net",
    icon: "📈",
    color: "amber",
    badge: "tool",
    cat: "tool",
  },
  {
    id: "it-hub",
    name: "IT HUB",
    desc: "NTI ticket & internal hub",
    url: "https://apex.oracle.com/pls/apex/r/nti_apps/nti-ticket/home",
    host: "apex.oracle.com",
    icon: "🔧",
    color: "green",
    badge: "tool",
    cat: "tool",
  },
  {
    id: "prithadevi",
    name: "PRITHADEVI",
    desc: "Prithadevi landing page",
    url: "http://leto.sonia.net:8080/ords/r/prithadevi/landingpage/landing-page",
    host: "leto.sonia.net",
    icon: "🏠",
    color: "cyan",
    badge: "prod",
    cat: "prod",
  },
  {
    id: "ibank-check",
    name: "IBANK CHECK",
    desc: "Internet banking checker",
    url: "http://leto.sonia.net:8080/ords/r/xtd/xtd-internet-banking-check/ibank-check",
    host: "leto.sonia.net",
    icon: "🏦",
    color: "amber",
    badge: "tool",
    cat: "tool",
  },
];

export const ERP_ENTITIES = [
  {
    name: "META",
    envs: [
      { name: "META PROD", env: "Production", url: "http://meta.niaganusaabadi.co.id:8000/", type: "prod" },
      { name: "META UAT",  env: "User Acceptance Test", url: "http://metauat.nna.net:8010/", type: "uat" },
    ],
  },
  {
    name: "NTI",
    envs: [
      { name: "NTI PROD", env: "Production", url: "http://ebs.ntiapps.net:8000/", type: "prod" },
      { name: "NTI DEV",  env: "Development", url: "http://spare.ntiapps.net:8003/", type: "dev" },
    ],
  },
  {
    name: "ATI",
    envs: [
      { name: "ATI PROD", env: "Production", url: "http://ati-ebs-apps.apps.net:8010/", type: "prod" },
      { name: "ATI DEV",  env: "Development", url: "http://ati-ebsdev.apps.net:8010/", type: "dev" },
    ],
  },
  {
    name: "NSTI",
    envs: [
      { name: "NSTI PROD", env: "Production", url: "http://nsti-ebs-apps.apps.net:8010/", type: "prod" },
      { name: "NSTI DEV",  env: "Development", url: "http://ebsdev.apps.net:8010/", type: "dev" },
    ],
  },
  {
    name: "NCT",
    envs: [
      { name: "NCT PROD", env: "Production", url: "http://nct-ebs-apps.apps.net:8010/", type: "prod" },
      { name: "NCT DEV",  env: "Development", url: "http://nct-ebsdev.apps.net:8010/", type: "dev" },
    ],
  },
];

export const ACTIVITIES = [
  { icon: "🚀", color: "cyan",   title: "FRITS v2.0 — Form Request IT System upgrade", meta: "APEX Cloud · Production", hash: "a3f2c1d" },
  { icon: "🏗️", color: "violet", title: "EAM preventive maintenance workflow added",    meta: "leto.sonia.net · Production", hash: "b7e81a2" },
  { icon: "📊", color: "green",  title: "IT HUB ticket dashboard revamped",              meta: "APEX Cloud · Tool", hash: "c9d45f3" },
  { icon: "🔧", color: "amber",  title: "PERMADI NTI MIS integration patch applied",     meta: "APEX Cloud · Production", hash: "d1f92b7" },
  { icon: "🏦", color: "cyan",   title: "IBANK CHECK: new validation rules deployed",    meta: "leto.sonia.net · Tool", hash: "e4a38c9" },
  { icon: "✨", color: "violet", title: "Portal revamp — glassmorphic UI upgrade",       meta: "GitHub · pandawa-apex", hash: "f2b19d4" },
];
